FROM debian:bullseye-slim AS build

RUN apt-get update && apt-get install -y \
curl \
git \
unzip \
xz-utils \
zip \
&& rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter
ENV PATH="${PATH}:/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin"
RUN flutter doctor -v


WORKDIR /app
COPY . .

RUN flutter pub get
RUN flutter build web --release --web-renderer html


FROM nginx:alpine

COPY --from=build /app/build/web /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]